//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Data
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class BindedInEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet BindedInEntities à l'aide de la chaîne de connexion trouvée dans la section 'BindedInEntities' du fichier de configuration d'application.
        /// </summary>
        public BindedInEntities() : base("name=BindedInEntities", "BindedInEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet BindedInEntities.
        /// </summary>
        public BindedInEntities(string connectionString) : base(connectionString, "BindedInEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet BindedInEntities.
        /// </summary>
        public BindedInEntities(EntityConnection connection) : base(connection, "BindedInEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Utilisateur> Utilisateur
        {
            get
            {
                if ((_Utilisateur == null))
                {
                    _Utilisateur = base.CreateObjectSet<Utilisateur>("Utilisateur");
                }
                return _Utilisateur;
            }
        }
        private ObjectSet<Utilisateur> _Utilisateur;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Utilisateur. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToUtilisateur(Utilisateur utilisateur)
        {
            base.AddObject("Utilisateur", utilisateur);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BindedInModel", Name="Utilisateur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Utilisateur : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Utilisateur.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété prenom.</param>
        public static Utilisateur CreateUtilisateur(global::System.Decimal id, global::System.String nom, global::System.String prenom)
        {
            Utilisateur utilisateur = new Utilisateur();
            utilisateur.id = id;
            utilisateur.nom = nom;
            utilisateur.prenom = prenom;
            return utilisateur;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                if (_nom != value)
                {
                    OnnomChanging(value);
                    ReportPropertyChanging("nom");
                    _nom = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nom");
                    OnnomChanged();
                }
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                if (_prenom != value)
                {
                    OnprenomChanging(value);
                    ReportPropertyChanging("prenom");
                    _prenom = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("prenom");
                    OnprenomChanged();
                }
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_naissance
        {
            get
            {
                return _date_naissance;
            }
            set
            {
                Ondate_naissanceChanging(value);
                ReportPropertyChanging("date_naissance");
                _date_naissance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_naissance");
                Ondate_naissanceChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_naissance;
        partial void Ondate_naissanceChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_naissanceChanged();

        #endregion

    
    }

    #endregion

    
}
